# Database connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ai_ecommerce}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:}

# PgVector configuration
spring.ai.vectorstore.pgvector.initialize-schema=false

# Run SQL scripts on startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

#Options: HNSW, IVFFLAT
spring.ai.vectorstore.pgvector.index-type=HNSW

#Options: COSINE_DISTANCE, EUCLIDEAN_DISTANCE, NEGATIVE_INNER_PRODUCT_DISTANCE
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536

# Optional settings
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.remove-existing-vector-store-table=false
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
